### ISSUE TITLE
Failed to activate the atom-deepscan package

### ISSUE THREAD

**Issue by ewilso4207** [deepscan/atom-deepscan#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-deepscan](https://github.com/deepscan/atom-deepscan) package 1.6.3

### Stack Trace

Failed to activate the atom-deepscan package

```
At Cannot find module 'convert-source-map'
Require stack:
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\lib\transformation\file\index.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\lib\api\node.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\index.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\atom-babel6-transpiler\lib\index.js
- C:\Users\1eric\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html

Error: Cannot find module 'convert-source-map'
Require stack:
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\lib\transformation\file\index.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\lib\api\node.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\babel-core\index.js
- C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\atom-babel6-transpiler\lib\index.js
- C:\Users\1eric\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-deepscan/node_modules/babel-core/lib/transformation/file/index.js:38:25)
    at /packages/atom-deepscan/node_modules/babel-core/lib/transformation/file/index.js:706:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-deepscan/node_modules/babel-core/lib/api/node.js:6:13)
    at /packages/atom-deepscan/node_modules/babel-core/lib/api/node.js:154:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-deepscan/node_modules/babel-core/index.js:1:173)
    at /packages/atom-deepscan/node_modules/babel-core/index.js:3:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at Object.transpile (/packages/atom-deepscan/node_modules/atom-babel6-transpiler/lib/index.js:50:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-deepscan 1.6.3 
busy-signal 2.0.1 
intentions 1.1.5 
linter 3.1.1 
linter-ui-default 2.1.4 
teletype 0.13.4 
```

**Comment by cimfalab** [comment]
So weird. When I just installed Atom 1.52.0 on my Windows 10 machine and the package, there was no error.

Do you have this error when you install the DeepScan package from Atom? Then, could you remove the package (if it's installed), restart Atom, and re-install the package?

**Comment by ewilso4207** [comment]
Yeah I did install it and it just said error but I do not want mess up with computer.

**Comment by wcho** [comment]
@ewilso4207 It seems that `convert-source-map` nodejs package is not installed correctly while installing `atom-deepscan` package. First check if `convert-source-map` exists in the path `C:\Users\1eric\.atom\packages\atom-deepscan\node_modules\convert-source-map`. And remove and reinstall `atom-deepscan` package. It will install the dependencies.
